#!/bin/bash

domain=$(sudo yunohost app setting shaarli_old_beta domain)

sudo rm -rf /var/www/shaarli_old
sudo rm -f /etc/nginx/conf.d/$domain.d/shaarli_old.conf
sudo rm -rf /home/yunohost.app/shaarli_old/data
